spring:
  profiles:
    group:
      test: local

  config:
    import:
      - application-oauth2.yml
      - application-db.yml
      - application-elastic.yml
  web:
    resources:
      add-mappings: false
  graphql:
    schema:
      locations:
        - classpath:graphql/**/

server:
  servlet:
    session:
      cookie:
        name: pofo_sid
        secure: true
        http-only: true
        path: /
      remember-me:
        name: pofo_rmm
        key: ${SESSION_REMEMBER_ME_KEY:not_secured_key}

---

spring:
  config:
    activate:
      on-profile: local

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

logging:
  level:
    org.pofo.api: DEBUG
    org.springframework.security: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

logging:
  level:
    org.pofo.api: INFO

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: ERROR
