spring.profiles.active: local

spring:
  config:
    import:
      - application-db.yml
  web:
    resources:
      add-mappings: false
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      locations:
        - classpath:graphql/**/

server:
  servlet:
    session:
      cookie:
        name: pofo_sid
        secure: true
        http-only: true
        path: /

session:
  remember-me-cookie:
    name: pofo_rmm
    secure: true
    http-only: true
    path: /
    token-validity-in-seconds: 604800 # 60 * 60 * 24 * 7

logging:
  level:
    org.pofo.api: DEBUG
    org.springframework.security: DEBUG
