spring:
  profiles:
    group:
      test: local

  config:
    import:
      - application-oauth2.yml
      - application-db.yml
      - application-elastic.yml
  web:
    resources:
      add-mappings: false
  graphql:
    schema:
      locations:
        - classpath:graphql/**/

jwt:
  secretKey: ${JWT_SECRET_KEY:not_secured_secretnot_secured_secretnot_secured_secretnot_secured_secretnot_secured_secret}

pofo:
  domain: ${POFO_DOMAIN:http://localhost:3000}

---

spring:
  config:
    activate:
      on-profile: local

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

logging:
  level:
    org.pofo.api: DEBUG
    org.springframework.security: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

logging:
  level:
    org.pofo.api: INFO

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: ERROR
