spring.profiles.active: local

spring:
  config:
    import:
      - application-db.yml
  web:
    resources:
      add-mappings: false
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      locations:
        - classpath:graphql/**/

server:
  servlet:
    session:
      cookie:
        name: pofo_sid
        secure: true
        http-only: true
        path: /
      remember-me:
        name: pofo_rmm
        token-key: development

logging:
  level:
    org.pofo.api: DEBUG
    org.springframework.security: DEBUG
