spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID:invalid_client_id}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET:invalid_client_secret}
            redirect-uri: ${OAUTH2_GITHUB_REDIRECT_URI:invalid_redirect_uri}
