services:
  postgresql:
    image: postgres:17.2-alpine3.20
    container_name: pofo_postgresql
    hostname: postgresql
    environment:
      - POSTGRES_PASSWORD=MyStrongcur3P@ssw0rd!
      - POSTGRES_DB=pofo
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]

  redis:
    image: redis:7.2.0-alpine
    container_name: pofo_redis
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIST_PASSWORD", "--raw", "incr", "ping" ]

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: pofo_opensearch
    hostname: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStrongcur3P@ssw0rd!
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    container_name: pofo_opensearch-dashboards
    hostname: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
