package org.pofo.domain.rds.domain.project;

public enum ProjectStack {
    JAVASCRIPT("JavaScript"),
	GITHUB("GitHub"),
	PYTHON("Python"),
	VISUAL_STUDIO_CODE("Visual Studio Code"),
	GIT("Git"),
	NODEDOTJS("Node.js"),
	REACT("React"),
	HTML5("HTML5"),
	DOCKER("Docker"),
	MYSQL("MySQL"),
	GMAIL("Gmail"),
	JAVA("Java"),
	TYPESCRIPT("TypeScript"),
	SLACK("Slack"),
	POSTGRESQL("PostgreSQL"),
	MONGODB("MongoDB"),
	POSTMAN("Postman"),
	NPM("npm"),
	GITLAB("GitLab"),
	JQUERY("jQuery"),
	CSS_3("CSS 3"),
	KUBERNETES("Kubernetes"),
	PHP("PHP"),
	GOOGLE_DRIVE("Google Drive"),
	NGINX("NGINX"),
	UBUNTU("Ubuntu"),
	JIRA("Jira"),
	ES6("ES6"),
	STACK_OVERFLOW("Stack Overflow"),
	INTELLIJ_IDEA("IntelliJ IDEA"),
	REDIS("Redis"),
	WORDPRESS("WordPress"),
	GOOGLE_ANALYTICS("Google Analytics"),
	GOOGLE_MAPS("Google Maps"),
	ANGULARJS("AngularJS"),
	VUEDOTJS("Vue.js"),
	CLOUDFLARE("CloudFlare"),
	SUBLIME_TEXT("Sublime Text"),
	ELASTICSEARCH("Elasticsearch"),
	CSHARP("C#"),
	JENKINS("Jenkins"),
	FIREBASE("Firebase"),
	AMAZON_WEB_SERVICES_("Amazon Web Services (AWS)"),
	VISUAL_STUDIO("Visual Studio"),
	SPRING_BOOT("Spring Boot"),
	TRELLO("Trello"),
	GITHUB_ACTIONS("GitHub Actions"),
	RABBITMQ("RabbitMQ"),
	MICROSOFT_AZURE("Microsoft Azure"),
	DJANGO("Django"),
	REACT_NATIVE("React Native"),
	GRAPHQL("GraphQL"),
	SASS("Sass"),
	EXPRESSJS("ExpressJS"),
	KAFKA("Kafka"),
	TERRAFORM("Terraform"),
	KIBANA("Kibana"),
	AMAZON_S3("Amazon S3"),
	GOOGLE_FONTS("Google Fonts"),
	AMAZON_EC2("Amazon EC2"),
	GOOGLE_CLOUD_PLATFORM("Google Cloud Platform"),
	PYCHARM("PyCharm"),
	REDUX("Redux"),
	STRIPE("Stripe"),
	GOOGLE_ADSENSE("Google AdSense"),
	VIM("Vim"),
	VIRTUALBOX("VirtualBox"),
	ANDROID_STUDIO("Android Studio"),
	AWS_LAMBDA("AWS Lambda"),
	ANDROID_SDK("Android SDK"),
	MARKDOWN("Markdown"),
	DATADOG("Datadog"),
	BITBUCKET("Bitbucket"),
	GRAFANA("Grafana"),
	CONFLUENCE("Confluence"),
	MICROSOFT_SQL_SERVER("Microsoft SQL Server"),
	APACHE_HTTP_SERVER("Apache HTTP Server"),
	FONT_AWESOME("Font Awesome"),
	PRETTIER("Prettier"),
	ASPDOTNET("ASP.NET"),
	YARN("Yarn"),
	AWS_ELASTIC_LOAD_BALANCING_DOTDOTDOT("AWS Elastic Load Balancing ..."),
	JQUERY_UI("jQuery UI"),
	GRADLE("Gradle"),
	HEROKU("Heroku"),
	PHPSTORM("PhpStorm"),
	SUPABASE("Supabase"),
	FLUTTER("Flutter"),
	WEBPACK("Webpack"),
	ESLINT("ESLint"),
	GOOGLE_TAG_MANAGER("Google Tag Manager"),
	RUBY("Ruby"),
	HUBSPOT("HubSpot"),
	AMAZON_CLOUDFRONT("Amazon CloudFront"),
	LARAVEL("Laravel"),
	NOTEPADPP("Notepad++"),
	SENTRY("Sentry"),
	ZENDESK("Zendesk"),
	APACHE_TOMCAT("Apache Tomcat"),
	KOTLIN("Kotlin"),
	SWIFT("Swift"),
	ANIMATEDOTCSS("Animate.css"),
	ANSIBLE("Ansible"),
	AMAZON_ROUTE_53("Amazon Route 53"),
	DOCKER_COMPOSE("Docker Compose"),
	FLASK("Flask"),
	SKYPE("Skype"),
	PYPI("PyPI"),
	SOCKETDOTIO("Socket.IO"),
	SELENIUM("Selenium"),
	AMAZON_CLOUDWATCH("Amazon CloudWatch"),
	OPENAPI("OpenAPI"),
	CPP("C++"),
	MAILCHIMP("Mailchimp"),
	NEXTDOTJS("Next.js"),
	JEST("Jest"),
	G_SUITE("G Suite"),
	SQLITE("SQLite"),
	MARIADB("MariaDB"),
	PAYPAL("PayPal"),
	TWILIO("Twilio"),
	AMAZON_EC2_CONTAINER_SERVICE("Amazon EC2 Container Service"),
	DIGITALOCEAN("DigitalOcean"),
	AMAZON_RDS("Amazon RDS"),
	WEBSTORM("WebStorm"),
	NEW_RELIC("New Relic"),
	GOOGLE_COMPUTE_ENGINE("Google Compute Engine"),
	DOTNET(".NET"),
	OBJECTIVE_C("Objective-C"),
	LOGSTASH("Logstash"),
	CIRCLECI("CircleCI"),
	ASANA("Asana"),
	GOOGLE_APP_ENGINE("Google App Engine"),
	MEMCACHED("Memcached"),
	DRUPAL("Drupal"),
	NESTJS("NestJS"),
	TWILIO_SENDGRID("Twilio SendGrid"),
	MICROSOFT_365("Microsoft 365"),
	PROMETHEUS("Prometheus"),
	ATOM("Atom"),
	INVISION("InVision"),
	SPRING("Spring"),
	DART("Dart"),
	RUST("Rust"),
	VERCEL("Vercel"),
	JUPYTER("Jupyter"),
	LINUX("Linux"),
	SONARQUBE("SonarQube"),
	CHATGPT("ChatGPT"),
	SHELL("Shell"),
	JEKYLL("Jekyll"),
	AIRFLOW("Airflow"),
	HADOOP("Hadoop"),
	ADOBE_ILLUSTRATOR("Adobe Illustrator"),
	ORACLE("Oracle"),
	TENSORFLOW("TensorFlow"),
	ARGO("Argo"),
	AMAZON_EKS("Amazon EKS"),
	MICROSOFT_SHAREPOINT("Microsoft SharePoint"),
	CONSUL("Consul"),
	NUXTDOTJS("Nuxt.js"),
	SCIKIT_LEARN("scikit-learn"),
	OPTIMIZELY("Optimizely"),
	ELIXIR("Elixir"),
	PLAYWRIGHT("Playwright"),
	OKTA("Okta"),
	GRPC("gRPC"),
	FFMPEG("FFMPEG"),
	DATABRICKS("Databricks"),
	ELEMENTOR("Elementor"),
	MONGODB_ATLAS("MongoDB Atlas"),
	GIN_GONIC("Gin Gonic"),
	PAGERDUTY("PagerDuty"),
	MILVUS("Milvus"),
	ONENOTE("OneNote"),
	BOTPRESS("Botpress"),
	SHINY("Shiny"),
	AMAZON_ELASTICACHE("Amazon ElastiCache"),
	R_LANGUAGE("R Language"),
	NIGHTWATCHJS("Nightwatchjs"),
	SNOWFLAKE("Snowflake"),
	FABRICDOTJS("Fabric.js"),
	HUGO("Hugo"),
	PHOENIX_FRAMEWORK("Phoenix Framework"),
	NEWMAN("Newman"),
	POWERSHELL("PowerShell"),
	GATSBY("Gatsby"),
	AWS_GLUE("AWS Glue"),
	CAMUNDA("Camunda"),
	SEQUELIZE("Sequelize"),
	GSTREAMER("GStreamer"),
	K3S("k3s"),
	SPRING_MVC("Spring MVC"),
	VAPOR("Vapor"),
	VISUAL_WEBSITE_OPTIMIZER("Visual Website Optimizer"),
	ORACLE_SQL_DEVELOPER("Oracle SQL Developer"),
	SERVERLESS("Serverless"),
	GOOGLE_DOMAINS("Google Domains"),
	REDASH("Redash"),
	XEN("Xen"),
	BENTHOS("Benthos"),
	ONESIGNAL("OneSignal"),
	CAFFE("Caffe"),
	JSONAPI("JsonAPI"),
	SPROUT_SOCIAL("Sprout Social"),
	RSTUDIO("RStudio"),
	INDEXEDDB("IndexedDB"),
	OPENNN("OpenNN"),
	CODA("Coda"),
	HOPPSCOTCH("Hoppscotch"),
	TASK("Task"),
	MICRONAUT_FRAMEWORK("Micronaut Framework"),
	VERTICA("Vertica"),
	LARAVEL_FORGE("Laravel Forge"),
	DEBEZIUM("Debezium"),
	IBM_DB2("IBM DB2"),
	PANDOC("Pandoc"),
	AMAZON_A_B_TESTING("Amazon A/B Testing"),
	ADOBE_ANALYTICS("Adobe Analytics"),
	STATSD("StatsD"),
	CYGWIN("Cygwin"),
	GOOGLE_OPTIMIZE("Google Optimize"),
	ELASTIC_CLOUD("Elastic Cloud"),
	VAADIN("Vaadin"),
	REDISGREEN("RedisGreen"),
	BUNDLER("Bundler"),
	SEARCHKICK("Searchkick"),
	BLACK_DUCK("Black Duck"),
	NETLIFY_CMS("Netlify CMS"),
	LANGCHAIN("LangChain"),
	PGVECTOR("pgvector"),
	SHOPIFY("Shopify"),
	XCODE("Xcode"),
	SYMFONY("Symfony"),
	RAILS("Rails"),
	OPENSSL("OpenSSL"),
	GITHUB_PAGES("GitHub Pages"),
	BABEL("Babel"),
	GOLANG("Golang"),
	TAILWIND_CSS("Tailwind CSS"),
	BOOTSTRAP("Bootstrap"),
	ELECTRON("Electron"),
	MACOS("macOS"),
	DROPBOX("Dropbox"),
	SOURCETREE("SourceTree"),
	FIGMA("Figma"),
	MICROSOFT_IIS("Microsoft IIS"),
	MODERNIZR("Modernizr"),
	ANGULAR("Angular"),
	TRAVIS_CI("Travis CI"),
	NOTION("Notion"),
	CENTOS("CentOS"),
	MOCHA("Mocha"),
	ENTITY_FRAMEWORK_CORE("Entity Framework Core"),
	MATERIAL_DESIGN_FOR_ANGULAR("Material Design for Angular"),
	OPENAI("OpenAI"),
	GOOGLE("Google"),
	VITE("Vite"),
	AMAZON_SES("Amazon SES"),
	SCALA("Scala"),
	GULP("gulp"),
	VAGRANT("Vagrant"),
	GRUNT("Grunt"),
	MINIO("Minio"),
	FASTAPI("FastAPI"),
	IONIC("Ionic"),
	MONDAYDOTCOM("monday.com"),
	CLAUDE("Claude"),
	DBEAVER("DBeaver"),
	OPENSSH("OpenSSH"),
	DISCORD("Discord"),
	N8N("n8n"),
	APOLLO("Apollo"),
	FASTIFY("Fastify"),
	GITLAB_CI("GitLab CI"),
	SWAGGER_UI("Swagger UI"),
	IOS("iOS"),
	VSCODEDOTDEV("vscode.dev"),
	MATERIAL_UI("Material-UI"),
	CUCUMBER("Cucumber"),
	PRISMA("Prisma"),
	LOKI("Loki"),
	MONGODB_COMPASS("MongoDB Compass"),
	GOLAND("GoLand"),
	FIREBASE_CLOUD_MESSAGING("Firebase Cloud Messaging"),
	DOTNET_CORE(".NET Core"),
	INSOMNIA_REST_CLIENT("Insomnia REST Client"),
	JETTY("Jetty"),
	KALI_LINUX("Kali Linux"),
	AZURE_APP_SERVICE("Azure App Service"),
	FACEBOOK_ADS("Facebook Ads"),
	LLM("LLM"),
	WHATSAPP("WhatsApp"),
	WIX("Wix"),
	ANACONDA("Anaconda"),
	KRAKEND("KrakenD"),
	PRESTASHOP("PrestaShop"),
	VAULT("Vault"),
	WEBFLOW("Webflow"),
	CDNJS("cdnjs"),
	LUA("Lua"),
	ELK("ELK"),
	JETBRAINS_RIDER("JetBrains Rider"),
	SQLALCHEMY("SQLAlchemy"),
	TORTOISESVN("TortoiseSVN"),
	TESTRAIL("Testrail"),
	COMPOSER("Composer"),
	VARNISH("Varnish"),
	JUNIT("JUnit"),
	SVN_("SVN (Subversion)"),
	SHADCN_UI("shadcn UI"),
	HASKELL("Haskell"),
	APACHE_MAVEN("Apache Maven"),
	VMWARE_VSPHERE("VMware vSphere"),
	OPENSTACK("OpenStack"),
	DATAGRIP("DataGrip"),
	PAPERTRAIL("Papertrail"),
	MIXPANEL("Mixpanel"),
	ONEDRIVE("OneDrive"),
	SWIFTUI("SwiftUI"),
	ASTRO("Astro"),
	SALESFORCE("Salesforce"),
	QUARKUS("Quarkus"),
	PNPM("pnpm"),
	GOOGLE_CHARTS("Google Charts"),
	DEVEXTREME("DevExtreme"),
	AWS_ELASTIC_BEANSTALK("AWS Elastic Beanstalk"),
	MICROSOFT_SQL_SERVER_MANAGEDOTDOTDOT("Microsoft SQL Server Manage..."),
	VISUAL_BASIC("Visual Basic"),
	FLOWBITE("Flowbite"),
	REMIX("Remix"),
	FIGJAM("FigJam"),
	LUNARVIM("LunarVim"),
	VERACODE("Veracode"),
	KTOR("Ktor"),
	AZURE_PIPELINES("Azure Pipelines"),
	BLAZOR("Blazor"),
	KUBEFLOW("Kubeflow"),
	PUPPETEER("Puppeteer"),
	TYPEORM("TypeORM"),
	WAZUH("Wazuh"),
	SPRING_SECURITY("Spring Security"),
	OLLAMA("Ollama"),
	LANGGRAPH("LangGraph"),
	CLOUDINARY("Cloudinary"),
	PERCONA_SERVER_FOR_MYSQL("Percona Server for MySQL"),
	TESTNG("TestNG"),
	PMD("PMD"),
	SANITY("Sanity"),
	KERAS("Keras"),
	MANJARO("Manjaro"),
	APACHE_JMETER("Apache JMeter"),
	TRAEFIK("Traefik"),
	JSON_WEB_TOKEN("JSON Web Token"),
	SNYK("Snyk"),
	DIRECTUS("Directus"),
	PUSHER("Pusher"),
	FIREBASE_AUTHENTICATION("Firebase Authentication"),
	HEIDISQL("HeidiSQL"),
	PINECONE("Pinecone"),
	APEX("Apex"),
	MASSTRANSIT("MassTransit"),
	GRAYLOG("Graylog"),
	MYSQL_WORKBENCH("MySQL WorkBench"),
	AZURE_DEVOPS("Azure DevOps"),
	PROTOBUF("Protobuf"),
	SOAP_UI("Soap UI"),
	METABASE("Metabase"),
	UPLOADCARE("Uploadcare"),
	AZURE_SQL_DATABASE("Azure SQL Database"),
	SEMRUSH("SEMrush"),
	SCRAPY("Scrapy"),
	GATLING("Gatling"),
	ROBOT_FRAMEWORK("Robot Framework"),
	GEOSERVER("GeoServer"),
	REPLIT("Replit"),
	GITHUB_ENTERPRISE("GitHub Enterprise"),
	BAZEL("Bazel"),
	APPIUM("Appium"),
	QT("Qt"),
	DROPWIZARD("Dropwizard"),
	MSSQL("MSSQL"),
	NATS("NATS"),
	SONATYPE_NEXUS("Sonatype Nexus"),
	RUBYMINE("RubyMine"),
	NODEMAILER("Nodemailer"),
	MARKETO("Marketo"),
	ENTITY_FRAMEWORK("Entity Framework"),
	NGROK("ngrok"),
	MATLAB("MATLAB"),
	CODESANDBOX("CodeSandbox"),
	HACK("Hack"),
	MONGOOSE("Mongoose"),
	JSON("JSON"),
	COCOAPODS("CocoaPods"),
	ECLIPSE("Eclipse"),
	ZOHO("Zoho"),
	TALEND("Talend"),
	ACTIVEMQ("ActiveMQ"),
	DOKUWIKI("DokuWiki"),
	NEOVIM("Neovim"),
	GOOGLE_CLOUD_STORAGE("Google Cloud Storage"),
	AZURE_FUNCTIONS("Azure Functions"),
	PROXMOX_VE("Proxmox VE"),
	UNITY("Unity"),
	RED_HAT_OPENSHIFT("Red Hat OpenShift"),
	GOOGLE_CLOUD_RUN("Google Cloud Run"),
	INTERCOM("Intercom"),
	ZAPIER("Zapier"),
	GNU_BASH("GNU Bash"),
	ARCH_LINUX("Arch Linux"),
	MKDOCS("MkDocs"),
	GOOGLE_KUBERNETES_ENGINE("Google Kubernetes Engine"),
	AMAZON_MECHANICAL_TURK("Amazon Mechanical Turk"),
	REAMAZE("Reamaze"),
	RAYGUN("Raygun"),
	AMAZON_CLOUDSEARCH("Amazon CloudSearch"),
	AG_GRID("AG Grid"),
	STACKDRIVER("Stackdriver"),
	WEBPAY("WEBPAY"),
	COREOS("CoreOS"),
	MAXCDN("MaxCDN"),
	MAILGUN("Mailgun"),
	SOLR("Solr"),
	FASTLANE("fastlane"),
	SEGMENT("Segment"),
	CRAZY_EGG("Crazy Egg"),
	APACHE_STORM("Apache Storm"),
	DISQUS("Disqus"),
	GOA("goa"),
	GRAPHICSMAGICK("GraphicsMagick"),
	QUICKBOOKS("QuickBooks"),
	POSTGREST("PostgREST"),
	CONTENTFUL("Contentful"),
	AMAZON_EMR("Amazon EMR"),
	HYPER("Hyper"),
	JSFIDDLE("JSFiddle"),
	SLICK("Slick"),
	PARSEHUB("ParseHub"),
	READ_THE_DOCS("Read the Docs"),
	RESHARPER("ReSharper"),
	GOOGLE_CLOUD_SQL("Google Cloud SQL"),
	COCOS2D_X("Cocos2D-X"),
	FIREHOSEDOTIO("Firehose.io"),
	ALGOLIA("Algolia"),
	APACHE_SPARK("Apache Spark"),
	LOMBOK("Lombok"),
	APACHE_THRIFT("Apache Thrift"),
	BOX("Box"),
	NUMPY("NumPy"),
	NEO4J("Neo4j"),
	FOREVER("forever"),
	MAILCATCHER("MailCatcher"),
	TSLINT("TSLint"),
	MAILTRAP("Mailtrap"),
	KODING("Koding"),
	PLANTUML("PlantUML"),
	FIBERY("Fibery"),
	AKKA("Akka"),
	FLUTTERFLOW("FlutterFlow"),
	HCAPTCHA("hCaptcha"),
	ROW_ZERO("Row Zero"),
	FRIGADE("Frigade"),
	GALERA_CLUSTER("Galera Cluster"),
	SPRING_FRAMEWORK("Spring Framework"),
	FSHARP("F#"),
	DATATABLES("DataTables"),
	NSQ("NSQ"),
	CLOSEDOTIO("Close.io"),
	XAMPP("XAMPP"),
	CLOUDMAILIN("Cloudmailin"),
	ZEPTO("Zepto"),
	GOOGLE_CLOUD_DATAFLOW("Google Cloud Dataflow"),
	POSTGIS("PostGIS"),
	POSTMARK("Postmark"),
	B_SECURE("B-SECURE"),
	INCAPSULA("Incapsula"),
	STATUSPAGEDOTIO("StatusPage.io"),
	BITLY("Bitly"),
	LOBE_CHAT("Lobe Chat"),
	READMEDOTIO("ReadMe.io"),
	TIGERGRAPH_DB("TigerGraph DB"),
	CONVERTKIT("ConvertKit"),
	MESSENGER_PLATFORM("Messenger Platform"),
	MODAL("Modal"),
	MICROSOFT_BOT_FRAMEWORK("Microsoft Bot Framework"),
	ATLASSIAN_COMPASS("Atlassian Compass"),
	SALESFORCE_EINSTEIN("Salesforce Einstein"),
	EXPLORE("Explore"),
	QUEUE_IT("Queue-it"),
	ARCHIUMDOTIO("Archium.io"),
	HIBERNATE("Hibernate"),
	SQUARESPACE("Squarespace"),
	CONFIGURE8("Configure8"),
	AIRPLANE("Airplane"),
	APPORTABLE("Apportable"),
	HANDLEBARSDOTJS("Handlebars.js"),
	AIRFOCUS("airfocus"),
	TWILIO_API_FOR_WHATSAPP("Twilio API for WhatsApp"),
	REASONML("ReasonML"),
	ANVIL("Anvil"),
	TWEETDECK("Tweetdeck"),
	RAML("RAML"),
	LARAVEL_VOYAGER("Laravel Voyager"),
	GOOGLE_CLOUD_SOURCE_REPOSITDOTDOTDOT("Google Cloud Source Reposit..."),
	TABLEPLUS("TablePlus"),
	MICROSOFT_ACCESS("Microsoft Access"),
	AZURE_ARC("Azure Arc"),
	ZAP("ZAP"),
	REFACTORDOTIO("Refactor.io"),
	MIDJOURNEY("Midjourney"),
	BRAINTREE("Braintree"),
	TAWKDOTTO("tawk.to"),
	CLOSURE_LIBRARY("Closure Library"),
	MEDIAWIKI("MediaWiki"),
	OPENCL("OpenCL"),
	DEPENDABOT("Dependabot"),
	COVERALLS("Coveralls"),
	SPRING_DATA("Spring Data"),
	HIGHCHARTS("Highcharts"),
	CLOUD_FUNCTIONS_FOR_FIREBASE("Cloud Functions for Firebase"),
	SEQUEL_PRO("Sequel Pro"),
	PHPPGADMIN("phpPgAdmin"),
	APACHE_FLUME("Apache Flume"),
	HETZNER_ONLINE_AG("Hetzner Online AG"),
	MOVEBOT("MoveBot"),
	LIBRENMS("LibreNMS"),
	TITAN("Titan"),
	GOOGLE_CLOUD_DEPLOYMENT_MANDOTDOTDOT("Google Cloud Deployment Man..."),
	HELIOS("Helios"),
	DBVISUALIZER("DbVisualizer"),
	DATOCMS("DatoCMS"),
	CUPY("CuPy"),
	OCTOPUS_DEPLOY("Octopus Deploy"),
	KONECTAR_KOL_MANAGEMENT_PLADOTDOTDOT("konectar KOL Management Pla..."),
	TEAMCITY("TeamCity"),
	GOGS("Gogs"),
	LAUNCHDARKLY("LaunchDarkly"),
	NETDATA("Netdata"),
	VERNEMQ("VerneMQ"),
	SKETCH("Sketch"),
	SOURCEGRAPH("Sourcegraph"),
	GITBOOK("Gitbook"),
	SEO4AJAX("SEO4Ajax"),
	LIVECHAT("LiveChat"),
	CRYPTPAD("CryptPad"),
	PLESK("Plesk"),
	GOOGLE_DOCS("Google Docs"),
	GREENSOCK("GreenSock"),
	TIMESCALEDB("TimescaleDB"),
	WKHTMLTOPDF("wkhtmltopdf"),
	PARSE("Parse"),
	AMAZON_LEX("Amazon Lex"),
	GOOGLE_CLOUD_CDN("Google Cloud CDN"),
	URBAN_AIRSHIP("Urban Airship"),
	KEYSTONEJS("KeystoneJS"),
	SURVEYMONKEY("SurveyMonkey"),
	MEDIUM("Medium"),
	FORK("Fork"),
	CHOCOLATEY("Chocolatey"),
	SPARKPOST("SparkPost"),
	PLOTLYDOTJS("Plotly.js"),
	CRUCIBLE("Crucible"),
	APACHE_CLOUDSTACK("Apache CloudStack"),
	MAPBOX("Mapbox"),
	WORKDAY("Workday"),
	NAMECHEAP("Namecheap"),
	ADYEN("Adyen"),
	IGNITE_UI("Ignite UI"),
	KOA("Koa"),
	OWNCLOUD("ownCloud"),
	GOOGLE_KEEP("Google Keep"),
	UIKIT("UIkIt"),
	CHARLES("Charles"),
	FRONT("Front"),
	PAW("Paw"),
	BINTRAY("BinTray"),
	HELLOSIGN("HelloSign"),
	HAPROXY("HAProxy"),
	SPLUNK("Splunk"),
	CONOHA("ConoHa"),
	WEBLATE("Weblate"),
	ODOO("Odoo"),
	OPENCV("OpenCV"),
	MIXMAX("Mixmax"),
	CRAFT("Craft"),
	TODOIST("Todoist"),
	ZIMBRA("Zimbra"),
	COLLECTD("collectd"),
	HERE_MAPS("Here Maps"),
	PUG("Pug"),
	FLUX_CD("Flux CD"),
	ADONISJS("AdonisJS"),
	ATSCALE("AtScale"),
	CAPISTRANO("Capistrano"),
	APACHE_FLINK("Apache Flink"),
	HYPER_TERMINAL("Hyper Terminal"),
	PREPROS("Prepros"),
	APP_ANNIE("App Annie"),
	AMAZON_REDSHIFT("Amazon Redshift"),
	AWS_CODEPIPELINE("AWS CodePipeline"),
	GHOSTSCRIPT("Ghostscript"),
	BROWSERSTACK("BrowserStack"),
	CODE_CLIMATE("Code Climate"),
	ORLEANS("Orleans"),
	BITDELI("Bitdeli"),
	MENDIX("Mendix"),
	HEROIC("Heroic"),
	DRUID("Druid"),
	KOWL("Kowl"),
	DOJO("Dojo"),
	BUFFER("Buffer"),
	CLEARBIT("Clearbit"),
	GAUGE("Gauge"),
	DOCKER_HUB("Docker Hub"),
	GEANY("Geany"),
	MESSAGEPACK("MessagePack"),
	CODIO("Codio"),
	OPENLAYERS("OpenLayers"),
	AMCHARTS("amCharts"),
	FIREBASE_REALTIME_DATABASE("Firebase Realtime Database"),
	ORIGAMI("Origami"),
	WEBDRIVERIO("WebdriverIO"),
	TYPEDB("TypeDB"),
	LIGHTWEIGHT_CHARTS("Lightweight Charts"),
	DELTA_LAKE("Delta Lake"),
	JSF("JSF"),
	HANGFIRE("Hangfire"),
	PUREBASIC("PureBasic"),
	JFROG_ARTIFACTORY("JFrog Artifactory"),
	NAMELY("Namely"),
	BOTKIT("Botkit"),
	QMETRY("QMetry"),
	GRAPHITE("Graphite"),
	PASSBOLT("Passbolt"),
	DREAMHOST("DreamHost"),
	MICROSOFT_EXCEL("Microsoft Excel"),
	WEBRTC("WebRTC"),
	RACKET("Racket"),
	MITHRIL("Mithril"),
	HELM("Helm"),
	SYBASE("Sybase"),
	TELEGRAM("Telegram"),
	REACT_TESTING_LIBRARY("react-testing-library"),
	MURALDOTCO("MURAL.co"),
	ZAMMAD("Zammad"),
	KUBUNTU("Kubuntu"),
	LOCALSTACK("LocalStack"),
	STYLED_COMPONENTS("styled-components"),
	JIB("Jib"),
	AZURE_DATABASE_FOR_POSTGRESQL("Azure Database for PostgreSQL"),
	CUBE("Cube"),
	VITESS("Vitess"),
	JAVALIN("Javalin"),
	OUTSYSTEMS("OutSystems"),
	COREDNS("CoreDNS"),
	LITEDB("LiteDB"),
	GLITCH("Glitch"),
	AWX("AWX"),
	SENSOR_TOWER("Sensor Tower"),
	HYPERLEDGER_FABRIC("Hyperledger Fabric"),
	AWS_FARGATE("AWS Fargate"),
	COINBASE("Coinbase"),
	SAFARI("Safari"),
	QT5("Qt5"),
	GOOGLE_MEET("Google Meet"),
	PRIMEREACT("PrimeReact"),
	VUE_NATIVE("Vue Native"),
	PIP("pip"),
	GOOGLE_CLOUD_BUILD("Google Cloud Build"),
	STRIPE_BILLING("Stripe Billing"),
	ANDROID_ROOM("Android Room"),
	APPLE_PUSH_NOTIFICATION_SERDOTDOTDOT("Apple Push Notification Ser..."),
	SNAPSEARCH("SnapSearch"),
	MYBATIS("MyBatis"),
	OPENFAAS("OpenFaaS"),
	WETRANSFER("WeTransfer"),
	CHAT_BY_STREAM("Chat by Stream"),
	ACTIX("Actix"),
	MATPLOTLIB("Matplotlib"),
	OPEN_INTERPRETER("Open Interpreter"),
	ITERM2("iTerm2"),
	SWIFTWEBUI("SwiftWebUI"),
	V_PROGRAMMING_LANGUAGE("V Programming Language"),
	GITDUCK("GitDuck"),
	REVENUECAT("RevenueCat"),
	APACHE_IGNITE("Apache Ignite"),
	KAFKA_STREAMS("Kafka Streams"),
	HEAP("Heap"),
	MQTT("MQTT"),
	IMGIX("imgix"),
	SILVERSTRIPE("SilverStripe"),
	TORBIT("Torbit"),
	JBOSS("JBoss"),
	FLARUM("Flarum"),
	SOLARWINDS("Solarwinds"),
	ANGULAR_GANTT("angular-gantt"),
	AMAZON_QUICKSIGHT("Amazon Quicksight"),
	PERFORCE("Perforce"),
	SUPERSONIC("Supersonic"),
	BLUEPRINT("Blueprint"),
	PHRASE("Phrase"),
	OCTOPARSE("Octoparse"),
	XWIKI("XWiki"),
	WEBGL("WebGL"),
	ATLASSIAN_STASH("Atlassian Stash"),
	NSERVICEBUS("NServiceBus"),
	ZOOM("Zoom"),
	FILEAGO("FileAgo"),
	GOOGLE_DATASTUDIO("Google Datastudio"),
	MUNIN("Munin"),
	XML("XML"),
	GOOGLE_CAMPAIGN_MANAGER("Google Campaign Manager"),
	CHATENGINE("ChatEngine"),
	LENS("Lens"),
	ZUSTAND("Zustand"),
	IBM_QRADAR("IBM QRadar"),
	MULE_RUNTIME_ENGINE("Mule runtime engine"),
	HARNESSDOTIO("Harness.io"),
	MONIT("Monit"),
	POSTWOMAN("Postwoman"),
	PYRIGHT("Pyright"),
	TABLEAU("Tableau"),
	CAPACITOR("Capacitor"),
	LOKALISE("Lokalise"),
	SMALLTALK("Smalltalk"),
	BEHAT("Behat"),
	OPENSTREETMAP("OpenStreetMap"),
	CHARTMOGUL("ChartMogul"),
	XOYONDO("Xoyondo"),
	GAMEMAKER_STUDIO_2("Gamemaker Studio 2"),
	HTTPIE("HTTPie"),
	STRONGDM("strongDM"),
	EMAILJS("EmailJS"),
	CODEKIT("CodeKit"),
	ZENCODER("Zencoder"),
	AMAZON_RDS_FOR_POSTGRESQL("Amazon RDS for PostgreSQL"),
	LAZARUS("Lazarus"),
	SALT("Salt"),
	GLEAM("Gleam"),
	V0_BY_VERCEL("v0 by Vercel"),
	CHATKIT("Chatkit"),
	GREENHOUSE("Greenhouse"),
	NETFLIX_OSS("Netflix OSS"),
	XAMARIN_FORMS("Xamarin Forms"),
	STORYBOOK("Storybook"),
	WITDOTAI("Wit.ai"),
	ANDROID_OS("Android OS"),
	CLICKHOUSE("Clickhouse"),
	CASSANDRA("Cassandra"),
	FATHOM_ANALYTICS("Fathom Analytics"),
	CLICKUP("ClickUp"),
	REACT_NAVIGATION("React Navigation"),
	CAKEPHP("CakePHP"),
	JITDOTIO("JIT.io"),
	MAPSTRUCT("MapStruct"),
	OPENRESTY("OpenResty"),
	CALENDLY("Calendly"),
	EMOTION("Emotion"),
	INFLUXDB("InfluxDB"),
	AWS_CLOUD9("AWS Cloud9"),
	GITLAB_PAGES("GitLab Pages"),
	RETROFIT("Retrofit"),
	BRACKETS("Brackets"),
	FIREBIRD("Firebird"),
	RANCHER("Rancher"),
	BATCH("Batch"),
	KONG("Kong"),
	SOCKETCLUSTER("SocketCluster"),
	LOCALIZE("Localize"),
	YEOMAN("Yeoman"),
	LAMBDATEST("LambdaTest"),
	GOOGLE_SITES("Google Sites"),
	QEMU("Qemu"),
	LIVESTORM("Livestorm"),
	PADDLE("Paddle"),
	HUBOT("Hubot"),
	NINJECT("Ninject"),
	CHARTDOTJS("Chart.js"),
	REDUX_OFFLINE("Redux Offline"),
	DYNATRACE("Dynatrace"),
	BLENDER("Blender"),
	XMIND("XMind"),
	RESTIFY("Restify"),
	LETS_ENCRYPT("Let's Encrypt"),
	ECHARTS("ECharts"),
	XLWINGS("xlwings"),
	LUCIDCHART("Lucidchart"),
	APPLAUSE("Applause"),
	MAPSDOTME("MAPS.ME"),
	LOCUST("Locust"),
	PYTEST("pytest"),
	TWIG("Twig"),
	KDEVELOP("KDevelop"),
	AIRTABLE("Airtable"),
	REACT_STORYBOOK("React Storybook"),
	NAVICAT("Navicat"),
	DOLIBARR("Dolibarr"),
	MICRO("Micro"),
	MOCKITO("Mockito"),
	TIPE("Tipe"),
	CANVASJS("CanvasJS"),
	VISUAL_STUDIO_LIVE_SHARE("Visual Studio Live Share"),
	AMAZON_PINPOINT("Amazon Pinpoint"),
	BOOTSWATCH("Bootswatch"),
	YESGRAPH("YesGraph"),
	GENESYS("Genesys"),
	OSSEC("Ossec"),
	PROJECT_REACTOR("Project Reactor"),
	SVELTE("Svelte"),
	VUETIFY("Vuetify"),
	GHOST_INSPECTOR("Ghost Inspector"),
	COVERITY_SCAN("Coverity Scan"),
	HOTJAR("Hotjar"),
	AUTOIT("AutoIt"),
	SQLPAD("SqlPad"),
	PROTONMAIL("ProtonMail"),
	FINDBUGS("FindBugs"),
	SLATE("Slate"),
	REACT_SKETCHDOTAPP("React Sketch.app"),
	ORA("Ora"),
	WINSCP("WinSCP"),
	ISTIO("Istio"),
	APACHE_CAMEL("Apache Camel"),
	APPWRITE("Appwrite"),
	MAILHOG("MailHog"),
	JACKSON("Jackson"),
	MOLECULER("Moleculer"),
	KEYBASE_TEAMS("Keybase Teams"),
	LINKERD("linkerd"),
	QLIKVIEW("QlikView"),
	BOOTSTRAP_VUE("Bootstrap Vue"),
	LINUX_MINT("Linux Mint"),
	PRIMEFACES("PrimeFaces"),
	ALLURE_REPORT("Allure Report"),
	VUEPRESS("VuePress"),
	MEMGRAPH("Memgraph"),
	EXPRESS_GATEWAY("Express Gateway"),
	ARANGODB("ArangoDB"),
	SPRING_BATCH("Spring Batch"),
	MLFLOW("MLflow"),
	DREMIO("Dremio"),
	REACT_REDUX("React Redux"),
	PHOTON("Photon"),
	POSTICO("Postico"),
	OPENNEBULA("OpenNebula"),
	STARSHIP_("Starship (Shell Prompt)"),
	ARVANCLOUD_CLOUD_SECURITY("ArvanCloud Cloud Security"),
	BUILDER("Builder"),
	NEPTUNE("Neptune"),
	PALZIN_TRACK("Palzin Track"),
	METAMON("Metamon"),
	COMPOSE("Compose"),
	APEX_PING("Apex Ping"),
	NODEGEAR("NodeGear"),
	CONTINUOUS_DELIVERY_SERVICE("Continuous Delivery Service"),
	SHIPWIRE("Shipwire"),
	AICONSOLE("AIConsole"),
	LLAMAFILE("Llamafile"),
	CONEMU("ConEmu"),
	LAUNCHPAGE_RAILS("launchpage-rails"),
	HIGHRISE("Highrise"),
	FLATSHEET("Flatsheet"),
	PRE_COMMIT_BY_YELP("pre-commit by Yelp"),
	SELLSY("Sellsy"),
	IRONMQ("IronMQ"),
	AMPERSANDDOTJS("Ampersand.js"),
	STRINGSDOTDEV("Strings.dev"),
	REPLICATED("Replicated"),
	FORMKEEP("FormKeep"),
	PROOFHUB("ProofHub"),
	CRMONE("CrmOne"),
	PHACILITY("Phacility"),
	GITCOLONY("Gitcolony"),
	HACKERONE("HackerOne"),
	ANGULARUI("AngularUI"),
	DELPHI("Delphi"),
	TABLETOPDOTJS("Tabletop.js"),
	DEMANDBASE("Demandbase"),
	OUTBRAIN("Outbrain"),
	SWIFTYBEAVER("SwiftyBeaver"),
	BUGFENDER("Bugfender"),
	JSHINT("JSHint"),
	LANGSTREAM("LangStream"),
	JUMPSUIT("Jumpsuit"),
	DRAW_A_UI("draw-a-ui"),
	ZENBU("Zenbu"),
	FRIENDS("Friends"),
	PARSEDOTLY("Parse.ly"),
	REACT_SERVER("React Server"),
	LIMELINE("Limeline"),
	CLOUDSTITCH("Cloudstitch"),
	APACHE_OOZIE("Apache Oozie"),
	BASELIME("Baselime"),
	EXPIRYDOTIO("Expiry.io"),
	BITBAR("BitBar"),
	PERFECT_AUDIENCE("Perfect Audience"),
	JUGGLINGDB("Jugglingdb"),
	SBT("SBT"),
	ESPRESSODOTJS("Espresso.js"),
	CHOCOLATECHIP_UI("ChocolateChip-UI"),
	FOGBUGZ("FogBugz"),
	STABLE_VIDEO_DIFFUSION("Stable Video Diffusion"),
	MOJOLICIOUS("Mojolicious"),
	UNBABEL("Unbabel"),
	OAUTHDOTIO("OAuth.io"),
	SPOCK_FRAMEWORK("Spock Framework"),
	RAILS_API("Rails API"),
	WIREEDIT("WireEdit"),
	FEATHERS("Feathers"),
	TRANSLATION_EXCHANGE("Translation Exchange"),
	AWS_SDK_FOR_KOTLIN("AWS SDK for Kotlin"),
	OSMEK("Osmek"),
	BLUEFLOOD("Blueflood"),
	BEANSTALKD("Beanstalkd"),
	NOMS("Noms"),
	BOTANALYTICS("Botanalytics"),
	CREATE_REACT_APP("Create React App"),
	FREEAGENT("FreeAgent"),
	TESTLODGE("TestLodge"),
	PROFITWELL("ProfitWell"),
	METEOR_GALAXY("Meteor Galaxy"),
	MITRO("Mitro"),
	AWS_SDK_FOR_RUST("AWS SDK for Rust"),
	SENCHA_EXT_JS("Sencha Ext JS"),
	STARLING("Starling"),
	ANGULAR_CLI("Angular CLI"),
	REVEAL_APP("Reveal App"),
	AMAZON_RDS_FOR_DB2("Amazon RDS for Db2"),
	TEMPODB("TempoDB"),
	SLACK_GITSIN("Slack Gitsin"),
	PALM_2("PaLM 2"),
	KIXIE("Kixie"),
	RIKO("riko"),
	AFTERSHIP("AfterShip"),
	ACTIONHERO("Actionhero"),
	LINQPAD("LINQPad"),
	TWILERT("Twilert"),
	REACT_ENGINE("React Engine"),
	REDBOOTH("Redbooth"),
	LMVTFY("LMVTFY"),
	AZURE_MACHINE_LEARNING("Azure Machine Learning"),
	LEVEL_3_CDN("Level 3 CDN"),
	JIRA_SERVICE_DESK("Jira Service Desk"),
	COMMON_LISP("Common Lisp"),
	SPRING_CLOUD("Spring Cloud"),
	UNICORNS("Unicorns"),
	CDI("CDI"),
	BISCUIT("Biscuit"),
	AMPLITUDE("Amplitude"),
	SUSY("Susy"),
	STACKER("Stacker"),
	BUGHERD("BugHerd"),
	ZOHO_CRM("Zoho CRM"),
	MATERIAL_KIT("Material Kit"),
	JIXEE("Jixee"),
	GOVISUALLY("GoVisually"),
	OBSERVIUM("Observium"),
	SKYPE_FOR_BUSINESS("Skype for Business"),
	WALKME("WalkMe"),
	SPARK_FRAMEWORK("Spark Framework"),
	LEANLABS_KANBAN("LeanLabs Kanban"),
	ORCHARD("Orchard"),
	DOMO("DOMO"),
	ALCHEMYAPI("AlchemyAPI"),
	FRACTL("Fractl"),
	ELASSANDRA("Elassandra"),
	RAMDA("Ramda"),
	KONNEKTIVE("Konnektive"),
	RIVER("River"),
	NODEPING("NodePing"),
	EMBER_CLI("Ember-cli"),
	INXMAIL("Inxmail"),
	CONTINUOUS("Continuous"),
	UBERALLS("uberalls"),
	ESCHER("Escher"),
	DRAFTJS("DraftJS"),
	BUTTON("Button"),
	IMPORTDOTIO("import.io"),
	BADGER("Badger"),
	DOMINO("Domino"),
	USERTESTING("UserTesting"),
	USERSNAP("Usersnap"),
	STACK("Stack"),
	BRAID("Braid"),
	GUMBY("Gumby"),
	ERRORCEPTION("Errorception"),
	DATAHERO("DataHero"),
	ACCOUNTABLE("Accountable"),
	MAPJAM("MapJam"),
	SIGNALFX("SignalFx"),
	STRIPE_ATLAS("Stripe Atlas"),
	CURSIVE("Cursive"),
	PENFLIP("Penflip"),
	STREAK("Streak"),
	FORMCRAFTS("FormCrafts"),
	SHIFTEDIT("ShiftEdit"),
	LIBRARIESDOTIO("Libraries.io"),
	FIREPAD("Firepad"),
	BITBALLOON("BitBalloon"),
	REVIEW_BOARD("Review Board"),
	RACKSPACE_ONMETAL("Rackspace OnMetal"),
	SEMANTRIA("Semantria"),
	WILLOW_LOGGING("Willow Logging"),
	GENTELELLA("gentelella"),
	UGLIFYJS("UglifyJS"),
	MASSIVE("Massive"),
	SAGUI("Sagui"),
	LINKURIOUS("Linkurious"),
	DATA_STUDIO("Data Studio"),
	NUTSHELL("Nutshell"),
	EBOOK_GLUE("Ebook Glue"),
	RACKSPACE_CLOUD_DATABASE("Rackspace Cloud Database"),
	FILEPREVIEWSDOTIO("FilePreviews.io"),
	PHPIXIE("PHPixie"),
	WAVE("Wave"),
	APPSIGNAL("AppSignal"),
	MICROSOFT_SSRS("Microsoft SSRS"),
	APPCUES("Appcues"),
	CHECKMK("Checkmk"),
	DJANGO_CMS("Django CMS"),
	APPTHWACK("AppThwack"),
	CAMERATAG("CameraTag"),
	VALENTINA_STUDIO("Valentina Studio"),
	CONTAINER_FACTORY("Container Factory"),
	VERSIONONE("VersionOne"),
	STATHAT("StatHat"),
	QUICKBLOX("QuickBlox"),
	APACHE_BEAM("Apache Beam"),
	LATERAL("Lateral"),
	API_PLUG("API Plug"),
	PROPROFS_KNOWLEDGE_BASE("ProProfs Knowledge Base"),
	WRIKE("Wrike"),
	MAILGEN("mailgen"),
	UXCAM("UXCam"),
	CAMPFIRE("Campfire"),
	LEVER_OS("Lever OS"),
	COALA("coala"),
	MOCKFLOW("MockFlow"),
	KVM("KVM"),
	RESPONDLY("Respondly"),
	IBM_NASA_GEOSPATIAL("IBM NASA Geospatial"),
	RUNBOOK("Runbook"),
	AWS_CLOUDHSM("AWS CloudHSM"),
	FOREST("Forest"),
	CODIAD("Codiad"),
	CONTAINERSHIP("ContainerShip"),
	SYMPHONY_CMS("Symphony CMS"),
	DOTCLOUD("dotCloud"),
	APTLY("aptly"),
	FLYDATA("FlyData"),
	DOORBELLDOTIO("Doorbell.io"),
	MOCKINGBIRD("Mockingbird"),
	DATAMEER("Datameer"),
	CDNIFY("CDNify"),
	EVERHOUR("Everhour"),
	ISTANBUL("Istanbul"),
	INTERAKT("Interakt"),
	UBERFLIP("Uberflip"),
	AWS_OPSWORKS("AWS OpsWorks"),
	PA_SERVER_MONITOR("PA Server Monitor"),
	VISUALOPS("VisualOps"),
	AWS_STORAGE_GATEWAY("AWS Storage Gateway"),
	HELPSTACK("HelpStack"),
	RESCUETIME("RescueTime"),
	DNS_MADE_EASY("DNS Made Easy"),
	CLOUD_CMS("Cloud CMS"),
	AZENDOO("Azendoo"),
	INFERNO("Inferno"),
	THUMBOR("Thumbor"),
	SCRUTINIZER("Scrutinizer"),
	SAPPER("Sapper"),
	LOGMX("LogMx"),
	GANGLIA("Ganglia"),
	TORUS("Torus"),
	DRIFT("Drift"),
	AMAZON_ELASTIC_TRANSCODER("Amazon Elastic Transcoder"),
	COTEDITOR("CotEditor"),
	GITORIOUS("Gitorious"),
	AMAZON_FPS("Amazon FPS"),
	CLOUDSPONGE("CloudSponge"),
	ROLLBAR("Rollbar"),
	WORKINGON("WorkingOn"),
	REACTPACK("Reactpack"),
	VECTOR("Vector"),
	HEX("Hex"),
	POME("Pome"),
	SMARTLING("Smartling"),
	REX("Rex"),
	NUNIT("NUnit"),
	DUCKRAILS("DuckRails"),
	COLOSSUS("Colossus"),
	SUPPORTFU("SupportFu"),
	KLIPFOLIO("Klipfolio"),
	RESINDOTIO("Resin.io"),
	SYMAS_LMDB("Symas LMDB"),
	AVOCADO("Avocado"),
	PLANABLE("Planable"),
	SMARTSTACK("SmartStack"),
	AIRSHIP("Airship"),
	VELOCITYDB("VelocityDB"),
	STACKIFY("Stackify"),
	SURFLY("Surfly"),
	PINGBOARD("Pingboard"),
	CANJS("CanJS"),
	HAKYLL("Hakyll"),
	SKAFFOLD("Skaffold"),
	AZURE_CONTAINER_SERVICE("Azure Container Service"),
	MONONOKE("Mononoke"),
	SCOOPDOTSH("Scoop.sh"),
	NESTOR("Nestor"),
	RESTDOTLI("Rest.li"),
	MAGNUM_CI("Magnum CI"),
	PRECURSOR("Precursor"),
	STORYLINE("Storyline"),
	LAMBDAPHP("LambdaPHP"),
	ASSEMBLY_LANGUAGE("Assembly Language"),
	CRAFT_CMS("Craft CMS"),
	BUILDMASTER("BuildMaster"),
	POSTSHARP("PostSharp"),
	TOLQ("Tolq"),
	SQUADLYTICS("Squadlytics"),
	OPERA_BROWSER("Opera Browser"),
	WECHAT_API("WeChat API"),
	AB_TASTY("AB Tasty"),
	BOTS_UI_KIT("Bots UI Kit"),
	QUERYSTORM("QueryStorm"),
	MOCKTASTIC("MOCKtastic"),
	PLUTIO("Plutio"),
	ROLLOUT("Rollout"),
	LITECOIN("Litecoin"),
	TILDA("Tilda"),
	DINERODOTJS("Dinero.js"),
	AWESOMPLETE("Awesomplete"),
	WUILT("Wuilt"),
	AEROFS("AeroFS"),
	COREDATA("CoreData"),
	SCRUMPY("Scrumpy"),
	MATOMO("Matomo"),
	TAXIFY("Taxify"),
	CLIPBOARDDOTJS("clipboard.js"),
	LOBE("Lobe"),
	SKOR("Skor"),
	REACTSTRAP("reactstrap"),
	GOOGLE_CLOUD_MEMORYSTORE("Google Cloud Memorystore"),
	ASKNED("AskNed"),
	FUSE_OPEN("Fuse Open"),
	CRUNCH_PNG("Crunch PNG"),
	TRAILS("Trails"),
	PERSONAS("Personas"),
	VUIDO("Vuido"),
	ORACLE_LINUX("Oracle Linux"),
	KUOLL("Kuoll"),
	CARRD("Carrd"),
	PORTWORX("Portworx"),
	LIST_AND_LABEL("List & Label"),
	FLUTE_MAIL_API("Flute Mail API"),
	COLLABTIVE("Collabtive"),
	TAXAMO("Taxamo"),
	SALESFORCE_COMMERCE_CLOUD("Salesforce Commerce Cloud"),
	MONETDB("MonetDB"),
	GOOGLE_CLOUD_TEXT_TO_SPEECH("Google Cloud Text-To-Speech"),
	FACEBOOK_SONAR("Facebook Sonar"),
	APACHE_XERCES("Apache Xerces"),
	REACT_ON_RAILS("React on Rails"),
	APPOPTICS("AppOptics"),
	KIALI("Kiali"),
	TYPEMOCK("Typemock"),
	RURU("Ruru"),
	LOOMIO("Loomio"),
	C3P0("C3P0"),
	_4D("4D"),
	CONDUCTRICS("Conductrics"),
	HATCHBOX("HatchBox"),
	DAILYCRED("DailyCred"),
	JAIME("Jaime"),
	ACCELQ("accelQ"),
	LAMBCI("LambCI"),
	ZIGGEO("Ziggeo"),
	JIRA_CORE("Jira Core"),
	VELOCITYDOTJS("Velocity.js"),
	CLICKSIGN("Clicksign"),
	ENGAGIO("Engagio"),
	DINGTALK("DingTalk"),
	TOYBOX("Toybox"),
	JSON_API("JSON API"),
	FLATPAK("Flatpak"),
	UMBRELLA_JS("Umbrella JS"),
	PAGEDRAW("Pagedraw"),
	HEYSPACE("HeySpace"),
	TILESTACHE("TileStache"),
	COMMITTASKS("CommitTasks"),
	REDUX_FORM("Redux Form"),
	REACT_MONOCLE("React Monocle"),
	TASKER("Tasker"),
	RUNNABLE("Runnable"),
	AMIUM("Amium"),
	GRAPEDROP("Grapedrop"),
	INTERCEPTDOTREST("Intercept.rest"),
	IZOOTO("iZooto"),
	AUTOTUNE("Autotune"),
	DEREK("derek"),
	OKTOPOST("Oktopost"),
	GRAPHQLDOTJS("graphql.js"),
	OMI("Omi"),
	REUSE("Reuse"),
	DIGITALOCEAN_MANAGED_DATABASES("DigitalOcean Managed Databases"),
	LOADNINJA("LoadNinja"),
	ZOHO_DOCS("Zoho Docs"),
	PROPEL("Propel"),
	GITGUARDIAN("GitGuardian"),
	OPENSTACK_SWIFT("Openstack Swift"),
	ARQUILLIAN("Arquillian"),
	DYSPATCH("Dyspatch"),
	LOGIFY("Logify"),
	INTERACTABLE("Interactable"),
	ZENTAO("ZenTao"),
	ADOBE_COLDFUSION("Adobe ColdFusion"),
	IONIDE("Ionide"),
	BOTMETRICS("Botmetrics"),
	MAILFLOSS("mailfloss"),
	PERFOPS_CLI("PerfOps CLI"),
	MIDTRANS("Midtrans"),
	COOLQLCOOL("CoolQLCool"),
	CODEBRAG("Codebrag"),
	KATRAN("Katran"),
	_8BASE("8base"),
	JOLOKIA("Jolokia"),
	BLUEPRINTS_APP("Blueprints app"),
	GRAPE_FOR_GITHUB("Grape for GitHub"),
	ZEND("Zend"),
	EXPERITEST("Experitest"),
	CACHEFLY("CacheFly"),
	_8X8("8x8"),
	LITECLI("LiteCLI"),
	SANIC("Sanic"),
	ALERTA("Alerta"),
	TIMESHEETS("Timesheets"),
	SERVO("Servo"),
	REACT_NATIVE_MATERIAL_DESIGN("React Native Material Design"),
	PYXLL("PyXLL"),
	VOID_LINUX("Void Linux"),
	FUZZBUZZ("Fuzzbuzz"),
	CODEGUARD("CodeGuard"),
	JSONNET("Jsonnet"),
	BALSAMIQ("Balsamiq"),
	THINGS("Things"),
	MOSCA("Mosca"),
	REACT_DRAGGABLE("React Draggable"),
	WAITLISTED("Waitlisted"),
	SPROUTVIDEO("SproutVideo"),
	FRAMEBENCH("Framebench"),
	CABOT("Cabot"),
	HACKNPLAN("HacknPlan"),
	COREZOID("Corezoid"),
	POSTSCRIPT("Postscript"),
	FRESHSALES("Freshsales"),
	ULTRALIGHT("Ultralight"),
	WASMER("Wasmer"),
	UI_BAKERY("UI Bakery"),
	WEBTREKK("Webtrekk"),
	MOSAIC("Mosaic"),
	ATOM_IDE("Atom-IDE"),
	PREVUE("PreVue"),
	FREELO("Freelo"),
	FUSE_FOR_MACOS("FUSE for macOS"),
	GOOGLE_CLOUD_HEALTHCARE_API("Google Cloud Healthcare API"),
	BENCHMARK_EMAIL("Benchmark Email"),
	GO_CHART("go-chart"),
	GOOGLE_TRAFFIC_DIRECTOR("Google Traffic Director"),
	SUITECRM("SuiteCRM"),
	SERVER_DENSITY("Server Density"),
	CHECKVIST("Checkvist"),
	DOME9("Dome9"),
	ARCHUNIT("ArchUnit"),
	MOBSTED("Mobsted"),
	JANETSH("Janetsh"),
	FORTRAN("Fortran"),
	DEVHINTS("Devhints"),
	JTOOLS("jTools"),
	REDLINE13("RedLine13"),
	MRDOT2("Mr.2"),
	TENSORFLOW_LITE("Tensorflow Lite"),
	CATJ("catj"),
	DPDK("DPDK"),
	VISUAL_SQL("Visual SQL"),
	AIRTAP("Airtap"),
	RAFAY_SYSTEMS("Rafay Systems"),
	PG_AMQP_BRIDGE("pg-amqp-bridge"),
	TOPSHELL("TopShell"),
	BACKLOG("Backlog"),
	DJAX_DMP_MANAGER("dJAX DMP Manager"),
	GLSL("GLSL"),
	RAPIDAPI("RapidAPI"),
	PULSE_SECURE("Pulse Secure"),
	AKKA_HTTP("Akka HTTP"),
	USERESPONSE("UseResponse"),
	M3_HEALTH("M3 Health"),
	RUST_ANALYZER("Rust-analyzer"),
	KOMPOSE("Kompose"),
	ASCII_TREE("Ascii Tree"),
	REACT_RAINBOW("React Rainbow"),
	QUOKKA("Quokka"),
	IODOTJS("io.js"),
	TRANSCEND("Transcend"),
	SPRING_EDGE("Spring Edge"),
	SPREADSHEETDB("SpreadsheetDB"),
	HANAMI("Hanami"),
	PROTON_NATIVE("Proton Native"),
	QUICKEMAILVERIFICATION("QuickEmailVerification"),
	SHOPIQ("ShopIQ"),
	ANBOX("Anbox"),
	PEOPLEHUM("peopleHum"),
	WEB3J("Web3j"),
	QONVERSION("Qonversion"),
	XOXODAY_EMPULS("Xoxoday Empuls"),
	MERCURY("Mercury"),
	COREUI_ICONS("CoreUI Icons"),
	XLTRAIL("Xltrail"),
	PINPOINT_SOFTWARE("Pinpoint Software"),
	ADAPTJS("AdaptJS"),
	PROTOACTOR("Protoactor"),
	TIEMPO("Tiempo"),
	PEZZO("Pezzo"),
	OPTIC("Optic"),
	SQUEALY("SQueaLy"),
	BOTIUM_SPEECH_PROCESSING("Botium Speech Processing"),
	MAILCOACH("Mailcoach"),
	MSMQ("MSMQ");

    private final String displayName;

    ProjectStack(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}
